version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image:  postgres
    environment:
      PGDTATA: /data/testdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin321
    volumes:
        - postgres:/data/postgres
    ports:
        - "5000:5432"
    networks:
        - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
volumes:
  postgres: